#!/bin/bash -e

src=$1

rm -rf system

get_file() {
   file=$1
   dst=$2

   if [ "$file_src" = "" ]; then
	adb pull /system/$file $dst
   else
	cp $src/system/$file $dst
   fi
}

for file in `grep '^[^#]' proprietary-files`
do
    dst=system/$file
    echo $dst...
    mkdir -p `dirname $dst`
    get_file $file $dst
done

# NOTE: I don't know anything about these so leaving them alone
# rm -rf optional
# for file in `grep '^[^#]' optional-files`
# do
#     dst=optional/$file
#     echo $dst...
#     mkdir -p `dirname $dst`
#     cp $src/system/$file dst
# done
